server:
  applicationConnectors:
    - type: http
      port: 10260
  adminConnectors:
    - type: http
      port: 10261
  allowedMethods:
    - GET
    - DELETE
    - PUT
    - POST

logging:
  level: INFO

swagger:
  resourcePackage: io.r0s.fwf.resources

graph:
  host: localhost
  port: 7687
  username: neo4j
  password: neo4j
