server:
  applicationConnectors:
    - type: http
      port: 10260
  adminConnectors:
    - type: http
      port: 10261

graphHost: localhost
graphPort: 7687
graphUsername: neo4j
graphPassword: neo4j
