version: "3.5"

services:
  neo4j:
    image: neo4j:3.5
    container_name: fwf-neo4j
    # volumes:
    #   - ./docker/data:/data
    restart: "no"
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
