spring:
  banner:
    location: classpath:banner.txt

server:
  port: 8080

logging:
  level:
    root: ERROR
    io.r0s.fwf: DEBUG

graph:
  host: localhost
  username: neo4j
  password: neo4j
  bolt:
    port: 7687
  http:
    port: 7474
