spring:
  banner:
    location: classpath:banner.txt
  boot:
    admin:
      client:
        instance:
          name: Flix with Friends Server
        url:
          - http://localhost:8080/gateway
      context-path: /gateway
  data:
    neo4j:
      embedded:
        enabled: false
      uri: bolt://localhost:7687
      username: neo4j
      password: neo4j

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints
# for admin client
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080

logging:
  level:
    root: ERROR
    io.r0s.fwf: DEBUG

---

spring:
  profiles: dev

logging:
  level:
    root: ERROR
    io.r0s.fwf: DEBUG

management:
  endpoint:
    shutdown:
      enabled: true

---

spring:
  profiles: docker
  data:
    neo4j:
      uri: bolt://fwf-neo4j:7687
